#! /usr/bin/env ruby
# because rubygems shims assume a gem's executables are Ruby

require "stripe-cli-ruby"

begin
  command = [ StripeCLI.executable, *ARGV ]
  exec(*command)
rescue StripeCLI::UnsupportedPlatformException, StripeCLI::ExecutableNotFoundException => e
  STDERR.puts("ERROR: " + e.message)
  exit 1
end
