name: Ruby

on:
  push:
    branches:
      # - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.2'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: gem install puma
      - run: bundle exec rake download
      - name: Run the default task
        run: bundle exec rake test
        env:
          TEST_STRIPE_API_KEY: ${{ secrets.TEST_STRIPE_API_KEY }}
